# Generated by Django 5.2.1 on 2025-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=40)),
                ('category_description', models.TextField()),
                ('category_pathImage', models.ImageField(blank=True, null=True, upload_to='assets/')),
            ],
        ),
    ]
