# Generated by Django 5.2.1 on 2025-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_pathImage',
            field=models.ImageField(blank=True, default='assets/default_card.jpg', null=True, upload_to='assets/'),
        ),
    ]
