# Generated by Django 5.2.1 on 2025-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0002_alter_card_card_pathimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_pathImage',
            field=models.ImageField(blank=True, default='assets/default.jpg', null=True, upload_to='assets/'),
        ),
    ]
