# Generated by Django 5.2.1 on 2025-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0003_alter_card_card_pathimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='assets/profile_img/default_img.jpg', null=True, upload_to='assets/profile_img/'),
        ),
    ]
